### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by JohnR89** [Floydan/discord-pickup-bot#46]
I was using the command !help but I dont understand for example, how one captain create a scrim for others join

**Comment by Floydan** [comment]
When creating a pickup queue you use the `!create` command

For example
`!create queuename 4`

Additional operator flags can be added, for instance
`!create "sunday night pickup" 4 -norcon -game Quake III -host server.address.com -port 12345

Available operators are:
- `-rcon`/`-norcon`
- `-game`
- `-host`
- `-port`
- `-coop`
- `-nocoop`
- `-novoice`
- `-gamemode`/`-gmode`
- `-gmode`
- `-game`
- `-teamsize`

The operators can also be used to update a pickup queue after it has been created with the same operators
`!update "sunday night pickup" -teamsize 3

**Comment by JohnR89** [comment]
Thanks by answer me fast, well if I use for example !create queuename, 4, not happens nothing

**Comment by Floydan** [comment]
the previous example I wrote had a minor spellingmistake where I accidentally added a `,` between queuename and teamsize

this is the correct one:
`!create queuename 4`

Did you add the bot to your server?

**Comment by JohnR89** [comment]
Yes I added by the link Bot Authorization. And I put this that you wrote me now, and still happens nothing. Maybe its my fault that I am doing something bad h

**Comment by Floydan** [comment]
Hmm, the link to add the discord bot to your server in the documentation might be old. The bot needs permissions to create channels, voice channels etc so the link might not have been updated to reflect that. Let me check and get back to you

**Comment by JohnR89** [comment]
Ok, thanks so much. I did this way, because I am not very good yet doing by myself the bot with the codes

**Comment by Floydan** [comment]
@JohnR89 if you type in the command `!version` what is shown?
Is the `Pickup bot` in the server users list?
Did you write the command in the `pickup` channel?

**Comment by JohnR89** [comment]
Oh ok sorry now I know which was the problem, like I have a long list of channels, I didnt see that channel, so sorry :(   .Yes now is working

**Comment by Floydan** [comment]
@JohnR89 Excellent, glad it works for you =) 
Let me know if there is anything else you need help with
